### ISSUE TITLE
SNMP walk on any node with Chronos installed crashes when the walk reaches the infinite table

### ISSUE THREAD

**Issue by graemerobertson** [Metaswitch/cpp-common#393]
```
Thread 207 (Thread 0x7f4987316700 (LWP 5840)):
#0  0x00007f498edbbb99 in waitpid () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f498ed412e2 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x000000000044f8bd in Logger::backtrace (this=0xc73080, data=0x7f4987312ed0 "Signal 6 caught\n") at /var/build/CC_8.0.0-WIP/cc/chronos/modules/cpp-common/src/logger.cpp:288
#3  0x000000000044eb63 in Log::backtrace (fmt=0x4cdd76 "Signal %d caught") at /var/build/CC_8.0.0-WIP/cc/chronos/modules/cpp-common/src/log.cpp:185
#4  0x0000000000493045 in signal_handler (sig=6) at /var/build/CC_8.0.0-WIP/cc/chronos/src/main/main.cpp:143
#5  <signal handler called>
#6  0x00007f498ed31cc9 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x00007f498ed350d8 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#8  0x00007f498f426535 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007f498f4246d6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007f498f424703 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007f498f424922 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#12 0x00007f498f476427 in std::__throw_out_of_range(char const*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x0000000000497f53 in std::vector<int, std::allocator<int> >::_M_range_check (this=0x7f4987315840, __n=0) at /usr/include/c++/4.8/bits/stl_vector.h:794
#14 0x0000000000497aeb in std::vector<int, std::allocator<int> >::at (this=0x7f4987315840, __n=0) at /usr/include/c++/4.8/bits/stl_vector.h:812
#15 0x0000000000496b00 in SNMP::InfiniteTimerCountTableImpl::netsnmp_table_handler_fn (this=0xc48180, handler=0xc48480, reginfo=0xc48500, reqinfo=0x1066b90, requests=0xf22620) at /var/build/CC_8.0.0-WIP/cc/chronos/modules/cpp-common/src/snmp_infinite_timer_count_table.cpp:175
#16 0x0000000000496781 in SNMP::InfiniteTimerCountTableImpl::static_netsnmp_table_handler_fn (handler=0xc48480, reginfo=0xc48500, reqinfo=0x1066b90, requests=0xf22620) at /var/build/CC_8.0.0-WIP/cc/chronos/modules/cpp-common/src/snmp_infinite_timer_count_table.cpp:112
#17 0x00007f498fbe19df in netsnmp_call_handlers () from /usr/lib/x86_64-linux-gnu/libnetsnmpagent.so.30
#18 0x00007f498fbeea99 in handle_var_requests () from /usr/lib/x86_64-linux-gnu/libnetsnmpagent.so.30
#19 0x00007f498fbf02c7 in handle_pdu () from /usr/lib/x86_64-linux-gnu/libnetsnmpagent.so.30
#20 0x00007f498fbf1458 in netsnmp_handle_request () from /usr/lib/x86_64-linux-gnu/libnetsnmpagent.so.30
#21 0x00007f498fbf1c92 in handle_snmp_packet () from /usr/lib/x86_64-linux-gnu/libnetsnmpagent.so.30
#22 0x00007f498f91efe1 in ?? () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.30
#23 0x00007f498f91fb6e in _sess_read () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.30
#24 0x00007f498f9209b9 in snmp_sess_read2 () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.30
#25 0x00007f498f920a0b in snmp_read2 () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.30
#26 0x00007f498f920a4c in snmp_read () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.30
#27 0x00007f498fbf1a4b in agent_check_and_process () from /usr/lib/x86_64-linux-gnu/libnetsnmpagent.so.30
#28 0x0000000000491933 in snmp_thread (data=0x0) at /var/build/CC_8.0.0-WIP/cc/chronos/modules/cpp-common/src/snmp_agent.cpp:47
#29 0x00007f49912d4182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#30 0x00007f498edf547d in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

I've got a fix but it seems to create a new problem, so I'm still working on it.

I've hit this by running snmpwalk on a node with Chronos installed.

I think it affects any node with Chronos installed, and is therefore critical for you @JimBunch. It's definitely critical for us.

**Comment by graemerobertson** [comment]
I tried to fix here - https://github.com/Metaswitch/cpp-common/pull/391, but now we're getting a new crash. Passing over to @rkd-msw.

```
Thread 210 (Thread 0x7f2c0c9ee700 (LWP 26676)):
#0  0x00007f2c14491b99 in __libc_waitpid (pid=26939, stat_loc=stat_loc@entry=0x7f2c0c9ea9a0, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
#1  0x00007f2c144172e2 in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:148
#2  0x000000000044f8e1 in Logger::backtrace (this=0x1de9ef0, data=0x7f2c0c9ead90 "Signal 6 caught\n") at /home/ubuntu/chronos/modules/cpp-common/src/logger.cpp:288
#3  0x000000000044eb87 in Log::backtrace (fmt=0x4cdbc8 "Signal %d caught") at /home/ubuntu/chronos/modules/cpp-common/src/log.cpp:185
#4  0x0000000000493113 in signal_handler (sig=6) at /home/ubuntu/chronos/src/main/main.cpp:143
#5  <signal handler called>
#6  0x00007f2c14407cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#7  0x00007f2c1440b0d8 in __GI_abort () at abort.c:89
#8  0x00007f2c14444394 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7f2c1455052b "*** %s ***: %s terminated\n") at ../sysdeps/posix/libc_fatal.c:175
#9  0x00007f2c144dbc9c in __GI___fortify_fail (msg=<optimized out>, msg@entry=0x7f2c14550513 "stack smashing detected") at fortify_fail.c:37
#10 0x00007f2c144dbc40 in __stack_chk_fail () at stack_chk_fail.c:28
#11 0x00000000004971c8 in SNMP::InfiniteTimerCountTableImpl::netsnmp_table_handler_fn (this=0x1db20a0, handler=0x1db23a0, reginfo=0x1db2420, reqinfo=0x7f2ba015a800, requests=0x0) at /home/ubuntu/chronos/modules/cpp-common/src/snmp_infinite_timer_count_table.cpp:231
#12 0x000000000049684f in SNMP::InfiniteTimerCountTableImpl::static_netsnmp_table_handler_fn (handler=0x1db23a0, reginfo=0x1db2420, reqinfo=0x7f2ba015a800, requests=0x7f2ba01a2ac0) at /home/ubuntu/chronos/modules/cpp-common/src/snmp_infinite_timer_count_table.cpp:112
#13 0x00007f2c152b79df in netsnmp_call_handlers () from /usr/lib/x86_64-linux-gnu/libnetsnmpagent.so.30
#14 0x00007f2c152c4a99 in handle_var_requests () from /usr/lib/x86_64-linux-gnu/libnetsnmpagent.so.30
#15 0x00007f2c152c626f in handle_pdu () from /usr/lib/x86_64-linux-gnu/libnetsnmpagent.so.30
#16 0x00007f2c152c7458 in netsnmp_handle_request () from /usr/lib/x86_64-linux-gnu/libnetsnmpagent.so.30
#17 0x00007f2c152c7c92 in handle_snmp_packet () from /usr/lib/x86_64-linux-gnu/libnetsnmpagent.so.30
#18 0x00007f2c14ff4fe1 in ?? () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.30
#19 0x00007f2c14ff5b6e in _sess_read () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.30
#20 0x00007f2c14ff69b9 in snmp_sess_read2 () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.30
#21 0x00007f2c14ff6a0b in snmp_read2 () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.30
#22 0x00007f2c14ff6a4c in snmp_read () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.30
#23 0x00007f2c152c7a4b in agent_check_and_process () from /usr/lib/x86_64-linux-gnu/libnetsnmpagent.so.30
#24 0x0000000000491a01 in snmp_thread (data=0x0) at /home/ubuntu/chronos/modules/cpp-common/src/snmp_agent.cpp:47
#25 0x00007f2c169aa182 in start_thread (arg=0x7f2c0c9ee700) at pthread_create.c:312
#26 0x00007f2c144cb47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by rkd-msw** [comment]
I've confirmed that removing both the infinite table from Chronos, and the proxy directives from snmpd.conf, works around this problem. @bossmc is checking that removing them is acceptable.

**Comment by rkd-msw** [comment]
@dcollins991 - I think this fix has been merged and you're retesting this. Please let me know if this is fixed (or if you're not expecting to retest this).

**Comment by dcollins991** [comment]
Tested yesterday.  Fixed.
