### ISSUE TITLE
Crash in AlarmReqAgent

### ISSUE THREAD

**Issue by AlexHockey** [Metaswitch/cpp-common#519]
#### Symptoms

A node that uses the alarm agent crashed with the following call stack:

```
#0  0x00007fc80c00fcc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fc80c0130d8 in __GI_abort () at abort.c:89
#2  0x00000000004da4e6 in signal_handler (sig=6) at main.cpp:201
#3  <signal handler called>
#4  0x00007fc80c00fcc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#5  0x00007fc80c0130d8 in __GI_abort () at abort.c:89
#6  0x00007fc80d014f39 in ?? () from /usr/lib/x86_64-linux-gnu/libzmq.so.3
#7  0x00007fc80d02baee in ?? () from /usr/lib/x86_64-linux-gnu/libzmq.so.3
#8  0x00007fc80d0182f7 in ?? () from /usr/lib/x86_64-linux-gnu/libzmq.so.3
#9  0x00007fc80d02cb06 in ?? () from /usr/lib/x86_64-linux-gnu/libzmq.so.3
#10 0x00007fc80d02d10f in ?? () from /usr/lib/x86_64-linux-gnu/libzmq.so.3
#11 0x00007fc80d040cd9 in ?? () from /usr/lib/x86_64-linux-gnu/libzmq.so.3
#12 0x00007fc80d040d49 in zmq_recv () from /usr/lib/x86_64-linux-gnu/libzmq.so.3
#13 0x000000000040dabd in AlarmReqAgent::agent (this=0x97dd40 <AlarmReqAgent::_instance>) at ../modules/cpp-common/src/alarm.cpp:481
#14 0x000000000040de59 in AlarmReqAgent::agent_thread (alarm_req_agent=<optimized out>) at ../modules/cpp-common/src/alarm.cpp:366
#15 0x00007fc80dd86182 in start_thread (arg=0x7fc801ffb700) at pthread_create.c:312
#16 0x00007fc80c0d347d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

#### Impact

Depends on the parent process, but it could lead to call failures (e.g. if sprout hit it). 

#### Release and environment 

Seen when using this cpp-common commit: 1daad3245832748a4ae8a0850b57a925f73462c3

#### Steps to reproduce

I wasn't doing anything specific at the time.

**Comment by eleanor-merry** [comment]
Fixed in https://github.com/Metaswitch/clearwater-snmp-handlers/pull/147
