### ISSUE TITLE
Crash when re-raising alarms

### ISSUE THREAD

**Issue by eleanor-merry** [Metaswitch/cpp-common#521]
#### Symptoms
I'm seeing Astaire crash reasonably regularly. The stack trace is:
```
#0  0x00007fd98afb0c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fd98afb4028 in __GI_abort () at abort.c:89
#2  0x000000000042778a in signal_handler (sig=11) at main.cpp:211
#3  <signal handler called>
#4  __GI___pthread_mutex_lock (mutex=0x0) at ../nptl/pthread_mutex_lock.c:66
#5  0x0000000000426075 in push_noblock (item=<error reading variable: access outside bounds of object referenced via synthetic pointer>, this=0x0)
    at ../modules/cpp-common/include/eventq.h:239
#6  AlarmReqAgent::alarm_request (this=this@entry=0x63bfc0 <AlarmReqAgent::_instance>, req=std::vector of length 3, capacity 3 = {...})
    at ../modules/cpp-common/src/alarm.cpp:358
#7  0x0000000000426591 in AlarmState::issue (this=0x176bfc0) at ../modules/cpp-common/src/alarm.cpp:71
#8  0x00000000004269b2 in reraise_last_state (this=<optimized out>) at ../modules/cpp-common/src/alarm.cpp:103
#9  AlarmManager::reraise_alarms (this=0x176baa0) at ../modules/cpp-common/src/alarm.cpp:257
#10 0x0000000000426a99 in AlarmManager::reraise_alarms_function (data=<optimized out>) at ../modules/cpp-common/src/alarm.cpp:225
#11 0x00007fd98c0db184 in start_thread (arg=0x7fd989a25700) at pthread_create.c:312
#12 0x00007fd98b07437d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

#### Release and environment 
Seen in the Farfetch'd release.

**Comment by eleanor-merry** [comment]
Possibly linked to https://github.com/Metaswitch/cpp-common/issues/519

**Comment by eleanor-merry** [comment]
This is another crash on shutdown/upgrade issue. I can reliably repro this by reducing the reraise alarm loop to 1 second and then stopping astaire. 

It happens because we typically stop the alarm req agent fairly early on in the shutdown process. If the reraise alarm thread wakes up and tries to resend the alarms it gets a stopped alarm req agent instance, and then tries to add a alarm to the deleted event queue, which crashes.
